### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by harikrishnajiju**
1]   removed the extra "/" at line 45 
2 ] also put the script tag in body to prevent "stray script tag from occurring" . 
     You can also put it in the head part of the code , but it may increase loading times.

### CODE REVIEW

**Comment by metzgegu** [comment]
Hello, thank you for your contribution, I didn't saw your Pull request and I already merged a PR which fix the extra "/".
But you can update your PR in order to fix your second fix :)

**Comment by harikrishnajiju** [comment]
I have already made the second fix with this PR as well. Should i make a different PR just for the 2nd fix?

**Comment by harikrishnajiju** [comment]
I have opened a new PR in patch - 2

**Comment by metzgegu** [comment]
I just merged patch-2 so I close this one

**Pull request closed without merging**
